import * as esbuild from "esbuild";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dist = join(__dirname, "dist");
const watch = process.argv.includes("--watch");

mkdirSync(dist, { recursive: true });

const entries = [
  { in: "src/background/service-worker.ts", out: "background/service-worker.js" },
  { in: "src/content/main.ts", out: "content/main.js" },
  { in: "src/popup/popup.ts", out: "popup/popup.js" },
  { in: "src/offscreen/terminal.ts", out: "offscreen/terminal.js" },
];

const buildOptions = {
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "chrome120",
  sourcemap: true,
  logLevel: "info",
};

function writeBundledStyles() {
  const overlayStyles = readFileSync(
    join(__dirname, "src/overlay/styles.css"),
    "utf-8"
  );
  const xtermStyles = readFileSync(
    join(__dirname, "node_modules/@xterm/xterm/css/xterm.css"),
    "utf-8"
  );
  const contents = `// Generated by build.mjs — do not edit.\nexport const overlayStyles = ${JSON.stringify(overlayStyles)};\nexport const xtermStyles = ${JSON.stringify(xtermStyles)};\n`;
  writeFileSync(join(__dirname, "src/overlay/bundled-styles.ts"), contents);
}

async function build() {
  writeBundledStyles();

  for (const entry of entries) {
    const isContentScript = entry.out === "content/main.js";
    const isOffscreen = entry.out === "offscreen/terminal.js";
    await esbuild.build({
      ...buildOptions,
      format: isContentScript || isOffscreen ? "iife" : buildOptions.format,
      entryPoints: [join(__dirname, entry.in)],
      outfile: join(dist, entry.out),
    });
  }

  copyFileSync(join(__dirname, "manifest.json"), join(dist, "manifest.json"));
  mkdirSync(join(dist, "popup"), { recursive: true });
  mkdirSync(join(dist, "overlay"), { recursive: true });
  copyFileSync(join(__dirname, "src/popup/popup.html"), join(dist, "popup/popup.html"));
  mkdirSync(join(dist, "offscreen"), { recursive: true });
  copyFileSync(
    join(__dirname, "src/offscreen/terminal.html"),
    join(dist, "offscreen/terminal.html")
  );
  copyFileSync(join(__dirname, "src/popup/popup.css"), join(dist, "popup/popup.css"));
  copyFileSync(join(__dirname, "src/overlay/styles.css"), join(dist, "overlay/styles.css"));
  copyFileSync(
    join(__dirname, "node_modules/@xterm/xterm/css/xterm.css"),
    join(dist, "overlay/xterm.css")
  );

  const manifest = JSON.parse(readFileSync(join(dist, "manifest.json"), "utf-8"));
  writeFileSync(join(dist, "manifest.json"), JSON.stringify(manifest, null, 2));
}

if (watch) {
  const ctx = await esbuild.context({
    ...buildOptions,
    entryPoints: entries.map((e) => join(__dirname, e.in)),
    outdir: dist,
    outbase: "src",
  });
  await build();
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await build();
  console.log("Build complete → dist/");
}
